language: node_js

notifications:
  email:
    on_success: never

jobs:
  include:
    - stage: "PHP"
      name: "PHPUnit"
      language: php
      php: 7.2
      script:
        - composer install
        # PHP Unit
        - composer run test
