language: node_js

notifications:
  email:
    on_success: never

node_js:
  - 8
  - 9
  - 10

script:
  - npm run lint
  - npm run test

  # PHP syntax check
  - bash -c '! (find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l | grep "Parse error")'
  # PHP cs fixer
  - vendor/bin/php-cs-fixer fix --no-interaction --dry-run --diff --rules=@PSR2 tests #classes controllers
  # PHP Unit
  - vendor/bin/phpunit tests/php
  # PHP Stan
  - if [ ${TRAVIS_PHP_VERSION:0:2} == "7." ]; then
      docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop;
      docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/web/module/tests/php/phpstan/phpstan.neon;
    fi
